"""user password is string

Revision ID: 488b7b89fd19
Revises: c251ccb9d00a
Create Date: 2021-12-22 19:01:02.388683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488b7b89fd19'
down_revision = 'c251ccb9d00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
