"""New Migration

Revision ID: 744ca286d1fe
Revises: bccafe308ff2
Create Date: 2021-12-22 17:57:15.421527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744ca286d1fe'
down_revision = 'bccafe308ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
