"""New Migration33

Revision ID: a20723938406
Revises: 744ca286d1fe
Create Date: 2021-12-22 18:24:57.742499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20723938406'
down_revision = '744ca286d1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
